apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  namespace: qed-kube-dev
spec:
  ports:
  - name: dask1
    port: 8786
    protocol: TCP
    targetPort: 8786
  - name: dask2
    port: 8787
    protocol: TCP
    targetPort: 8787W
  selector:
    app: dask-scheduler
  type: ClusterIP
