apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: dask-scheduler
  name: dask-scheduler
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      containers:
      - args:
        - dask-scheduler
        image: dbsmith88/dask-scheduler:latest
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8786
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8786
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        name: dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
      dnsPolicy: ClusterFirst
      hostname: dask-scheduler
      restartPolicy: Always
