apiVersion: v1
kind: Service
metadata:
  name: nta-django
  namespace: qed-kube-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nta-django
  type: ClusterIP
