apiVersion: v1
kind: Service
metadata:
  name: nta-nginx
spec:
  selector:
    app: nta-nginx
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 443
      name: http
  type: LoadBalancer
