apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nta-django
  name: nta-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nta-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nta-django
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: nta-config
        image: ghcr.io/quanted/nta_app:dev-k
        imagePullPolicy: Always
        name: nta-django
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /src/nta_app/collected_static
          name: collected-static
        - mountPath: /src/app-data
          name: app-data
        # - mountPath: /src/nta_app  #for local deployment mounts
        #   name: django-code
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      # volumes:  # For local deployments
      #   - name: collected-static
      #     hostPath:
      #       path: /host/collected-static
      #   - name: app-data
      #     hostPath:
      #       path: /host/app-data
      #   - name: django-code
      #     hostPath:
      #       path: /host/django-code
      volumes:  # For AWS deployment
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1
