apiVersion: v1
kind: Service
metadata:
  name: nta-dask-scheduler
spec:
  ports:
  - name: dask1
    port: 8786
    protocol: TCP
    targetPort: 8786
  - name: dask2
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: nta-dask-scheduler
  type: ClusterIP
