apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nta-dask-worker
  name: nta-dask-worker
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nta-dask-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nta-dask-worker
    spec:
      containers:
      - image: dbsmith88/nta-dask:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        name: nta-dask-worker
      dnsPolicy: ClusterFirst
      hostname: nta-dask-worker
      restartPolicy: Always
      schedulerName: default-scheduler
