apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nta-mongodb
  name: nta-mongodb
  namespace: qed-kube-dev
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: nta-mongodb
  serviceName: nta-mongodb
  template:
    metadata:
      labels:
        app: nta-mongodb
    spec:
      containers:
      - image: dbsmith88/mongodb:latest
        imagePullPolicy: Always
        command: ['mongod']
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        name: nta-mongodb
        readinessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: nta-mongodb-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: nta-mongodb-pvc
        persistentVolumeClaim:
          claimName: nta-mongodb-pvc
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
