apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nta-django
  name: nta-django
  namespace: qed-kube-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nta-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nta-django
    spec:
      containers:
      - env:
        - name: DJANGO_SETTINGS_MODULE
          value: settings
        - name: SECRET_KEY
          value: "wx$p52y!1p!*p$$y^d!f9@5=)3o#88+08-i9_mc8*-8h+x2&@w"
        - name: DASK_SCHEDULER
          value: nta-dask-scheduler:8786
        - name: MONGO_SERVER
          value: nta-mongodb:27017
        image: dbsmith88/nta-django:dev-k
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        name: nta-django
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /src/collected_static
          name: collected-static
        - mountPath: /src/app-data
          name: app-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1
