apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nta-django
  name: nta-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nta-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nta-django
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: nta-config
        image: dbsmith88/nta-django:dev-k
        imagePullPolicy: Always
#        readinessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 30
#        resources:
#          requests:
#            memory: "512Mi"
#            cpu: "250m"
#          limits:
#            memory: "1Gi"
#            cpu: "1000m"
        name: nta-django
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /src/nta_app/collected_static
          name: collected-static
        - mountPath: /src/app-data
          name: app-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
#      volumes:
#        - name: collected-static
#          hostPath:
#            path: /host/collected-static
#        - name: app-data
#          hostPath:
#            path: /host/app-data
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1
