apiVersion: v1
kind: PersistentVolume
metadata:
  name: collected-static-pv
  namespace: qed-kube-dev
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: C:\git\nta\data\nginx
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collected-static-pvc
  namespace: qed-kube-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
